### ISSUE TITLE
Lack of Proper Documentation

### ISSUE THREAD

**Issue by dominichackett** [bnb-chain/greenfield-js-sdk#15]
I am trying to upload a file which I expected to be a trivial task. I followed the wallet example.  How do I actually prepare and sign the object for upload? There needs to be more code examples

**Comment by rrr523** [comment]
Sorry for replying so late. The repo is still under rapid development.

In fact, we already have examples of upload files. Please check [object](https://github.com/bnb-chain/greenfield-js-sdk/blob/alpha/examples/wallet/src/components/object/create/index.tsx) example
