### ISSUE TITLE
GenOffChainAuthKeyPairAndUpload fails

### ISSUE THREAD

**Issue by layinka** [bnb-chain/greenfield-js-sdk#301]
**SDK version**:
0.2.4

**Environment**:
- **OS** (e.g. from /etc/os-release): Windows 11
- **Install tools**:
- **Others**: Angular 16, Typescript 5 

**What happened**:
Issue using the greenfield JS SDK on our dapp where client.offchainauth.genOffChainAuthKeyPairAndUpload fails after signing msg using metamask while trying to get the offChain Auth Keys with the following error:

`Object { code: -1, message: "value is undefined", statusCode: 404 }`

**What you expected to happen**:
It should return the Offchain Auth Res

**Have you tried the latest version**: yes/no
Yes
**How to reproduce it** (as minimally and precisely as possible):
We are following the NextJs example 

```
const offchainAuthRes = await client.offchainauth.genOffChainAuthKeyPairAndUpload(
    {
      sps: allSps,
      chainId: environment.greenfieldChainId,
      expirationMs: 5 * 24 * 60 * 60 * 1000,
      domain: window.location.origin,
      address,
    },
    provider,
  );
```

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**: N/A

**Anything else we need to know**: N/A

**Comment by clydemeng** [comment]
Is possible to provide a curl cmd (or any other form), which represents your http request?  Ideally please provide the http response as well.

**Comment by rrr523** [comment]
Could you please provide the actual values of these parameters so that we can reproduce them if there is a problem.
