### ISSUE TITLE
Weird behaviour for downloadFile

### ISSUE THREAD

**Issue by AndrewChupin** [bnb-chain/greenfield-js-sdk#476]
I have store "open-store" with some files there, I can get info for such files, but when I'm trying to download it I get an error.
Actually all operations with "authType" or "privateKey" is failing.
I've changed private key, just for you to understand format. 

Client info:
```
    const client = Client.create(
        "https://gnfd-testnet-fullnode-tendermint-us.bnbchain.org:443",
        "greenfield_5600-1",
    );
```    

Code:
<img width="642" alt="image" src="https://github.com/bnb-chain/greenfield-js-sdk/assets/15245196/5510683b-c10f-4a83-94a8-5a4ef333490e">

Error:
<img width="1090" alt="image" src="https://github.com/bnb-chain/greenfield-js-sdk/assets/15245196/258eb9dc-2f4c-47ec-acc0-d4f99141a61e">

**Comment by rrr523** [comment]
`object.downloadFile` is for use in the browser.

If you want to download file on Nodejs, you can use `client.object.getObject`.

ref: https://docs.bnbchain.org/greenfield-docs/docs/tutorials/dapp/js-file-management/overview/#41-download-object

**Comment by AndrewChupin** [comment]
<img width="1265" alt="image" src="https://github.com/bnb-chain/greenfield-js-sdk/assets/15245196/959856ec-24d5-4038-b151-502170b5b02f">

What should be the private key format??

**Comment by AndrewChupin** [comment]
Added 0x, now it works, thanks
