### ISSUE TITLE
Greenfield Create Object 400 Error

### ISSUE THREAD

**Issue by emreaslan7** [bnb-chain/greenfield-js-sdk#477]
hi I try to create object on greenfield everthing is correct but I got error like this: I know expiration time doesn't exist yet. I checked it with the Unix converter and everything is correct. I follow next.js example repo. SAME with me 😦 Help please

![image](https://github.com/bnb-chain/greenfield-js-sdk/assets/76620402/5fbdfb96-a5eb-4d25-932b-4e6f1c2be664)

![image](https://github.com/bnb-chain/greenfield-js-sdk/assets/76620402/87fcb05d-2d04-4f64-a500-3cfe0553c4cd)

HOW THAT HAPPENS. I think there is an error in this section. But I did everything the same, what should I do to fix this? 

![image](https://github.com/bnb-chain/greenfield-js-sdk/assets/76620402/1ca9f545-bf1b-4584-b6e1-620b0a60970a)

// import {Client} from '@bnb-chain/greenfield-js-sdk'
import {Client} from '@bnb-chain/greenfield-js-sdk'
import {ReedSolomon} from '@bnb-chain/reed-solomon'

export const createObjectToGreenfield = async (provider, signer, jsonMetadata) => {
  const userAddress = await signer.getAddress()
  console.log('signer', signer)

  const client = await createClientToGreenfield()

  const offChainData = await getOffchainAuthKeys(client, userAddress, provider, signer)

  const jsonString = JSON.stringify(jsonMetadata, null, 2)

  const blob = new Blob([jsonString], {type: 'application/json'})
  const rs = new ReedSolomon()
  const fileBytes = await blob.arrayBuffer()
  const expectCheckSums = rs.encode(new Uint8Array(fileBytes))

  const createObjectTx = await createObjecTxToGreenfield(
    client,
    blob,
    fileBytes,
    expectCheckSums,
    offChainData,
    userAddress
  )

  const createObjectTxSimulateInfo = await createObjectTx.simulate({
    denom: 'BNB',
  })

  console.log('simulate sonucu', createObjectTxSimulateInfo)

  const createObjectTxRes = await createObjectTx.broadcast({
    denom: 'BNB',
    gasLimit: Number(createObjectTxSimulateInfo?.gasLimit),
    gasPrice: createObjectTxSimulateInfo?.gasPrice || '5000000000',
    payer: userAddress,
    granter: '',
  })

  console.log('brodcast sonucu', createObjectTxRes)

  await uploadObjectToGreenfield(createObjectTxRes, client, blob, offChainData, userAddress)

  await getObjectPreviewUrlToGreenfield(client, userAddress, offChainData)
}

const createClientToGreenfield = async () => {
  // const client = Client.create('https://gnfd-testnet-fullnode-tendermint-ap.bnbchain.org', 5600)
  const client = Client.create('https://gnfd-testnet-fullnode-tendermint-ap.bnbchain.org', '5600', {
    zkCryptoUrl: 'https://unpkg.com/@bnb-chain/greenfield-zk-crypto@0.0.3/dist/node/zk-crypto.wasm',
  })
  return client
}

const createObjecTxToGreenfield = async (
  client,
  blob,
  fileBytes,
  expectCheckSums,
  offChainData,
  userAddress
) => {
  let createObjectTx
  console.log('expectCheckSums', expectCheckSums)
  console.log('userAddress', userAddress)
  console.log('offChainData', offChainData)
  try {
    createObjectTx = await client.object.createObject(
      {
        bucketName: 'opbnbemredeneme001',
        objectName: 'metadata009.json',
        creator: userAddress,
        visibility: 'VISIBILITY_TYPE_PUBLIC_READ',
        fileType: 'json',
        redundancyType: 'REDUNDANCY_EC_TYPE',
        contentLength: 13111,
        expectCheckSums: expectCheckSums,
        tags: {
          tags: [],
        },
      },
      {
        type: 'EDDSA',
        domain: window.location.origin,
        seed: offChainData.seedString,
        address: userAddress,
      }
    )
    console.log('createObjectTx', createObjectTx)
    return createObjectTx
  } catch (error) {
    console.log('error', error)
    return
  }
}

const uploadObjectToGreenfield = async (createObjectTxRes, client, blob, offChainData, address) => {
  const uploadRes = await client.object.uploadObject(
    {
      bucketName: 'opbnbemredeneme001',
      objectName: 'metadata009.json',
      body: blob,
      txnHash: createObjectTxRes.transactionHash,
    },
    {
      type: 'EDDSA',
      domain: window.location.origin,
      seed: offChainData.seedString,
      address,
    }
  )

  console.log('upload object', uploadRes)

  if (uploadRes.code === 0) {
    console.log('upload object success', uploadRes)
  }
}

const getObjectPreviewUrlToGreenfield = async (client, userAddress, offChainData) => {
  const res = await client.object.getObjectPreviewUrl(
    {
      bucketName: 'opbnbemredeneme001',
      objectName: 'metadata009.json',
      queryMap: {
        view: '1',
        'X-Gnfd-User-Address': userAddress,
        'X-Gnfd-App-Domain': window.location.origin,
        'X-Gnfd-Expiry-Timestamp': '2024-09-03T09%3A23%3A39Z',
      },
    },
    {
      type: 'EDDSA',
      domain: window.location.origin,
      seed: offChainData.seedString,
      address: userAddress,
    }
  )

  console.log('getObjectPreviewUrlToGreenfield', res)
  return res
}

const getSps = async (client) => {
  const sps = await client.sp.getStorageProviders()
  const finalSps = (sps ?? []).filter((v) => v.endpoint.includes('nodereal'))
  return finalSps
}

const getAllSps = async (client) => {
  const sps = await getSps(client)

  return sps.map((sp) => {
    return {
      address: sp.operatorAddress,
      endpoint: sp.endpoint,
      name: sp.description?.moniker,
    }
  })
}

const getOffchainAuthKeys = async (client, address, provider, signer) => {
  const storageResStr = localStorage.getItem(address)

  if (storageResStr) {
    const storageRes = JSON.parse(storageResStr)
    console.log('storageResStr', storageRes.expirationTime)
    console.log('Date.now()', Date.now())

    if (storageRes.expirationTime < Date.now()) {
      alert('Your auth key has expired, please generate a new one')
      localStorage.removeItem(address)
      return
    }

    return storageRes
  }

  const allSps = await getAllSps(client)

  try {
    const offchainAuthRes = await client.offchainauth.genOffChainAuthKeyPairAndUpload(
      {
        sps: allSps,
        chainId: 1017,
        expirationMs: 5 * 24 * 60 * 60 * 1000,
        domain: window.location.origin,
        address,
      },
      window.ethereum
    )
    console.log('offchainAuthRes', offchainAuthRes)
    const {code, body: offChainData} = offchainAuthRes
    if (code !== 0 || !offChainData) {
      throw offchainAuthRes
    }
    console.log('offChainData', offChainData)

    localStorage.setItem(address, JSON.stringify(offChainData))
    return offChainData
  } catch (error) {
    console.log('error', error)
  }
}

**Comment by rrr523** [comment]
The message "user public key is expired" indicates that the offchainAuth you applied for is not in the same bucket as the object you are trying to create.

If you are using code from examples, you can try recreating a bucket and then creating an object in that bucket.

**Comment by CocoStarZ** [comment]
@emreaslan7 do you still have any questions? if no, we will close the issue. thx
