### ISSUE TITLE
client.bucket.createBucket return fetch is not defined

### ISSUE THREAD

**Issue by Zhang-Tianxu** [bnb-chain/greenfield-js-sdk#482]
**1.2.0**:

**Environment**:
- **OS** (e.g. from /etc/os-release): windows 11 professional 
- **Install tools**: npm
- **Others**: node version **16.18.1**, npm version **9.2.0**

**What happened**: `index.js` in `examples/nodejs-file-management` work properly, but `storage.js`  not

**What you expected to happen**: example work properly, bucket can be created at least

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible): 

        `cd examples/nodejs-file-management` -> `npm install` -> `node storage.js`

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

![image](https://github.com/bnb-chain/greenfield-js-sdk/assets/19359257/e2717a4e-4623-4c44-8b80-d05021ea8050)
**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Anything else we need to know**:

**Comment by STdevK** [comment]
Please upgrade to Node.js v17.5.0 or higher to enable Fetch API support

**Comment by Zhang-Tianxu** [comment]
Thanks! 

I upgrade to 17.5.0, but still not working, it will be appreciated if you could tell me how to enable Fetch API support.

![image](https://github.com/bnb-chain/greenfield-js-sdk/assets/19359257/0249db61-a5b7-4e54-9ea6-a75ca5122395)

**Comment by STdevK** [comment]
Can you share the link to your codes? May need to look the codes as a whole

**Comment by CocoStarZ** [comment]
@Zhang-Tianxu do you still have any problem? if no we will close this issue. thx
