### ISSUE TITLE
Unable to use client.sp

### ISSUE THREAD

**Issue by wsehl** [bnb-chain/greenfield-js-sdk#51]
**SDK version**: 0.2.0

**Environment**:
- **OS** (e.g. from /etc/os-release): MacOS
- **Install tools**: pnpm
- **Others**:

**What happened**:
Methods using client.sp doesnt work and always result in this error
<img width="960" alt="Screen Shot 2023-05-24 at 15 10 03" src="https://github.com/bnb-chain/greenfield-js-sdk/assets/47861945/f46f5c28-04a7-44dd-ba0e-f487835cbc34">

**What you expected to happen**:
expect it to work

**Have you tried the latest version**: yes/no
yes

**How to reproduce it** (as minimally and precisely as possible):
1. clone the repo
2. follow this [guide](https://github.com/bnb-chain/greenfield-js-sdk/tree/alpha/examples/nextjs#install-and-build)

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
```
Uncaught (in promise) Error: Query failed with (6): unknown query path: unknown request
    at QueryClient.queryAbci (queryclient.js:134:19)
    at async Object.request (utils.js:35:30)
    at async Sp.getStorageProviders (index.js:5568:21)
    at async onClick (index.tsx:70:41)
```

**Config (you can paste only the changes you've made)**:
no changes, default config ```.env.simple```

**node command runtime flags**:

**Anything else we need to know**:

**Comment by rrr523** [comment]
Sorry, you have to fill your config in env file.

check https://github.com/bnb-chain/greenfield-js-sdk/issues/52#issuecomment-1561649247
