### ISSUE TITLE
Timeout on uploadObject is not respected

### ISSUE THREAD

**Issue by haal** [bnb-chain/greenfield-js-sdk#517]
**SDK version**: 1.2.3

**Environment**:
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 11 (bullseye) (docker)
- **Install tools**: 
- **Others**:

**What happened**:
Uploading larger file (eg 15MB) failed with request timeout after 30sec even with `duration` field set to 200sec on `client.object.uploadObject`

**What you expected to happen**:
Request timeout should not occur at least until 200 sec.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
Try example from `examples/nodejs/cases/storage.js` where `filePath` points to a larger file.
```
  const uploadRes = await client.object.uploadObject(
    {
      bucketName: bucketName,
      objectName: objectName,
      body: fileBuffer,
      txnHash: createObjectTxRes.transactionHash,
      duration: 200000,
    },
    {
      type: 'ECDSA',
      privateKey: ACCOUNT_PRIVATEKEY,
    },
  );
```

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
Error with message `'request time out` is returned.

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Anything else we need to know**:
I think this could be caused by the code in [spClient.ts](https://github.com/bnb-chain/greenfield-js-sdk/blob/main/packages/js-sdk/src/clients/spclient/spClient.ts#L59) where `timeout` param from method is not used in `fetchWithTimeout` (which has 30 sec default).

**Comment by rrr523** [comment]
@haal Thank you so much for checking our code.

It fixed #523

**Comment by rrr523** [comment]
1.2.4 released

**Comment by haal** [comment]
Thanks a lot for fixing and releasing this so fast!
