### ISSUE TITLE
PutPolicy shows error if expirationTime is put in statement object.

### ISSUE THREAD

**Issue by rawat07102** [bnb-chain/greenfield-js-sdk#518]
**SDK version**:  1.2.3

**Environment**:
- **OS** (e.g. from /etc/os-release): windows 10

**What happened**:

if I add "expirationTime" field in statement object, I get following error, but if I remove "expirationTime" it works fine.

**What you expected to happen**:
The policy should have expirationTime, on which it expires

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
- add expirationTime field in statement object.
![image](https://github.com/bnb-chain/greenfield-js-sdk/assets/46820045/e18010fc-4f6f-4d8d-aba3-68a46cb5bae4)

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**: ![image](https://github.com/bnb-chain/greenfield-js-sdk/assets/46820045/4e2835aa-2656-4b6f-b695-b90aa3742e97)

**Anything else we need to know**:
It works as intended if I remove expirationTime field from statement object, but gives error if I add the field back.

**Comment by rrr523** [comment]
Thanks for feedback.

Fixed in #524

**Comment by rrr523** [comment]
1.2.4 released

**Comment by rawat07102** [comment]
It still give me the same error, no matter where I put the expirationTime field, either in or outside statement object. but works without expirationTime. Am I doing something wrong ?

![image](https://github.com/bnb-chain/greenfield-js-sdk/assets/46820045/51968769-6283-4a46-bf2f-dec1e64224b5)

**Comment by rrr523** [comment]
@rawat07102 

What's `expirationTime` value? Can you log it?
