### ISSUE TITLE
A import issues when running the javascript script using Node.js

### ISSUE THREAD

**Issue by luchenqun** [bnb-chain/greenfield-js-sdk#519]
**SDK version**:2.0.0-alpha.6 or 1.2.3

**Environment**:
- **OS** (e.g. from /etc/os-release): MacOS
- **Install tools**: NPM
- **Others**:

**What happened**:
client.js file
```js
import { Client } from '@bnb-chain/greenfield-js-sdk';

const client = Client.create('https://gnfd-testnet-fullnode-tendermint-ap.bnbchain.org', '5600');

console.log(client);

```

excute `node client.js` error happen

import { Client } from '@bnb-chain/greenfield-js-sdk';
         ^^^^^^
SyntaxError: Named export 'Client' not found. The requested module '@bnb-chain/greenfield-js-sdk' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@bnb-chain/greenfield-js-sdk';
const { Client } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.11.0

**What you expected to happen**:
import { Client } from '@bnb-chain/greenfield-js-sdk';**NO ERROR HAPPEN.**

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Anything else we need to know**: If you change the above client.js to client.ts and execute the script using ts-node, there should be no issue. Are you not planning to support JavaScript anymore and only support TypeScript? Or what needs to be done to support JavaScript?

**Comment by rrr523** [comment]
em... [CommonJS](https://nodejs.org/api/modules.html) is required in the Nodejs environment.

That means:

```js
const { Client } = require('@bnb-chain/greenfield-js-sdk');

const client = Client.create('https://gnfd-testnet-fullnode-tendermint-ap.bnbchain.org', '5600');
console.log(client);
```

**Comment by rrr523** [comment]
> I see that the examples provided by the official documentation are all ECMAScript modules, such as: https://docs.bnbchain.org/greenfield-js-sdk/client/greenfield-client/. So, can it support ECMAScript modules? Because most npm libraries now prioritize supporting ECMAScript modules. Is supporting ECMAScript modules technically challenging?

Oh, the documentation is wrong. We'll fix it.

As for using the ESM in Nodejs, if not after the module bundler(Webpack, vite, etc) is compiled, may need to look at https://nodejs.org/api/esm.html, this is not to do the package at this level.
