### ISSUE TITLE
Project is not building

### ISSUE THREAD

**Issue by prenl** [bnb-chain/greenfield-js-sdk#52]
**SDK version**: 0.2.0 (latest on 05/24/2023)

**Environment**:
- **OS**: Windows 10 22H2
- **Install tools**: pnpm

**What happened**:
I did everything as described in the readme (./examples/nextjs), but when I run the command ```pnpm run -r build```, it keeps giving me an error.

![image](https://github.com/bnb-chain/greenfield-js-sdk/assets/79540438/c5e589ee-c002-4dc1-8514-ccbef666dc5f)

**What you expected to happen**:
To build a project and run it through ```npm run dev```

**Have you tried the latest version**: yes/no
yes

**How to reproduce it** (as minimally and precisely as possible):
1) ```git clone https://github.com/bnb-chain/greenfield-js-sdk```
2) ```cd greenfield-js-sdk/``` (also gives some warns)
3) ```pnpm install```
4) ```cd examples/nextjs/```
5) ```cp .env.simple .env.development.local```
6) ```pnpm run -r build```
7) gives an error after some time of building

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
```
└─ Running...
../nodejs build$ cross-env NODE_ENV=development next build
│ "cross-env" �� ���� ����७��� ��� ���譥�
│ ��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
└─ Failed in 27ms at C:\Users\prenl\Рабочий стол\greenfield-js-sdk\examples\nodejs
C:\Users\prenl\Desktop\greenfield-js-sdk\examples\nodejs:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @demo/nodejs@0.0.4 build: `cross-env NODE_ENV=development next build`
Exit status 1
```

**Config (you can paste only the changes you've made)**:
I didn't change anything after performing git clone

**Anything else we need to know**:
I've been trying to do that on macOS 13.4 (Macbook Air M2) and It was giving me the same error

**Comment by rrr523** [comment]
Sorry, you have to fill your config in env file.

for example:

```
NEXT_PUBLIC_GRPC_URL=https://gnfd-testnet-fullnode-tendermint-us.bnbchain.org
NEXT_PUBLIC_GREENFIELD_RPC_URL=https://gnfd-testnet-fullnode-tendermint-us.bnbchain.org/ethapi
NEXT_PUBLIC_GREEN_CHAIN_ID=5600
NEXT_PUBLIC_BSC_RPC_URL=https://gnfd-bsc-testnet-dataseed1.bnbchain.org
NEXT_PUBLIC_BSC_CHAIN_ID=5601
NEXT_PUBLIC_TOKEN_HUB_CONTRACT_ADDRESS=0x10C6E9530F1C1AF873a391030a1D9E8ed0630D26
NEXT_PUBLIC_CROSS_CHAIN_CONTRACT_ADDRESS=0xeEBe00Ac0756308ac4AaBfD76c05c4F3088B8883
```
