### ISSUE TITLE
invalid payload data integrity hash

### ISSUE THREAD

**Issue by HelloRickey** [bnb-chain/greenfield-js-sdk#537]
**SDK version**:
    "@bnb-chain/greenfield-js-sdk": "^2.0.0",
    "@bnb-chain/reed-solomon": "^1.1.3",

**Environment**:
- **OS** (e.g. from /etc/os-release): mac
- **Install tools**:
- **Others**:node v18.0.0

**What happened**:

I found that greenfield-js-sdk has a problem when uploading json files to Object. Only json files have this problem, other files are normal

I use this method to build https://github.com/bnb-chain/greenfield-js-sdk/tree/main/packages/reed-solomon#nodejs

`
const { ReedSolomon } = require('@bnb-chain/reed-solomon')
const rs = new ReedSolomon();
const res = await rs.encode(Uint8Array.from(fileBuffer));
`

When I upload Object, it will prompt me 
`{
  code: '110004',
  message: 'invalid payload data integrity hash',
  statusCode: 406
}`
https://github.com/HelloRickey/greenfield-test/blob/main/index.js#L97

But when I use Nodejs **(worker_threads)**
it will succeed
https://github.com/HelloRickey/greenfield-test/blob/main/index.js#L21

**Comment by rrr523** [comment]
Sorry, we didn't update the example in time.

After `2.x`, we don't need to compute hashes anymore, just use `delegateUploadObject `: https://github.com/bnb-chain/greenfield-js-sdk/blob/main/packages/js-sdk/tests/upload.spec.ts#L26

ref PR: https://github.com/bnb-chain/greenfield-js-sdk/pull/500

**Comment by HelloRickey** [comment]
gsdg45sd4g5s4dg5sdトオジビタからロピカなフアやャクヤなどがミドっぱくラバニラサ

**Comment by HelloRickey** [comment]
Hey @rrr523 , I use `delegateUploadObject`, but it still doesn't work for json files and prompts new problems.
https://github.com/bnb-chain/greenfield-js-sdk/issues/539
