### ISSUE TITLE
my-gnfd-app demo app create bucket error

### ISSUE THREAD

**Issue by bond-aspecta** [bnb-chain/greenfield-js-sdk#545]
**SDK version**:
2.0.0

**Environment**:
- **OS** (e.g. from /etc/os-release):MacOS Sonoma
- **Install tools**: 
- **Others**:

**What happened**:
<img width="1918" alt="image" src="https://github.com/bnb-chain/greenfield-js-sdk/assets/106575310/bdd739f1-daaf-4dd5-8609-23c0b9718b9a">

**What you expected to happen**:
It should create a bucket without errors.

**Have you tried the latest version**: yes/no
The latest template? Yes.

**How to reproduce it** (as minimally and precisely as possible):
Just follow steps in the quickstart docs page. https://docs.bnbchain.org/greenfield-js-sdk/getting-started/quick-start

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
No log.

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Anything else we need to know**:

**Comment by rrr523** [comment]
@bond-aspecta 

What's `createBucket` function's params?

**Comment by rrr523** [comment]
@bond-aspecta 

Our demo app has just been updated to the latest sdk version, you can try it again now.
