### ISSUE TITLE
Check cosmos boroadcast issue

### ISSUE THREAD

**Issue by AndrewChupin** [bnb-chain/greenfield-js-sdk#565]
**SDK version**: 
    "@bnb-chain/bsc-cross-greenfield-sdk": "^0.0.3",
    "@bnb-chain/greenfield-contracts": "^1.2.2",
    "@bnb-chain/greenfield-contracts-sdk": "^1.1.0",
    "@bnb-chain/greenfield-js-sdk": "^2.1.1",
    "@bnb-chain/reed-solomon": "^1.1.3",
    "@openzeppelin/contracts": "^5.0.1"

**Environment**:
- **OS** (e.g. from /etc/os-release): MacOs
- **Install tools**: Node 22.8.0
- **Others**:

**What happened**:
During object creation I get an error `Broadcasting transaction failed with code 4 (codespace: sdk). Log: wrong number of signers; expected 2, got 1: unauthorized`, looks like it's expecting multisig account, but the signing account isn't.

**What you expected to happen**:
Check an error

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
Try to create an object:
```

    const rs = new NodeAdapterReedSolomon();
    const fileBuffer = fs.readFileSync("/Users/andrew/Documents/test1.txt");
    const expectCheckSums = await rs.encodeInWorker(__filename, Uint8Array.from(fileBuffer));

    const createObjectTx = await client.object.createObject({
        creator: '0X7EEE0E672244F9F199C4D5B644D4351D14EE7D41',,
        bucketName: "blabla3",
        objectName: "test1.txt",
        payloadSize: Long.fromInt(3),
        visibility: VisibilityType.VISIBILITY_TYPE_INHERIT,
        contentType: "text/plain",
        expectChecksums: expectCheckSums.map((x: any) => bytesFromBase64(x)),
        redundancyType: RedundancyType.REDUNDANCY_EC_TYPE,
    })

    const createObjectTxSimulateInfo = await createObjectTx.simulate({
        denom: 'BNB',
    });

    const createObjectTxRes = await createObjectTx.broadcast({
        denom: 'BNB',
        gasLimit: Number(createObjectTxSimulateInfo?.gasLimit),
        gasPrice: createObjectTxSimulateInfo?.gasPrice || '5000000000',
        payer: '0X7EEE0E672244F9F199C4D5B644D4351D14EE7D41',
        granter: '',
        privateKey: `0xd16966ade9664e5c20a6f87da5df38ca2a35eb0d9e9f1034acb51faaaf151fd1`,
    });

    console.log("Object created:", createObjectTxRes.transactionHash)
```

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:
yarn hardhat run scripts/altdev.ts --network bsc_test

**Anything else we need to know**:

**Comment by AnirudhThadem** [comment]
Hey @AndrewChupin I am also facing the same issue.. Did you find any workaround for this issue
