### ISSUE TITLE
create payment account error

### ISSUE THREAD

**Issue by Bioneisme** [bnb-chain/greenfield-js-sdk#61]
**SDK version**:0.2.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Win10
- **Others**: node v16.17.0, npm v8.15.0

**What happened**: It is not possible to create a payment account due to a number of errors

Using simulation method this error comes out: 
![image](https://github.com/bnb-chain/greenfield-js-sdk/assets/92920845/1cbabb53-0a47-4e4e-89e8-7ad6dc4ae6bc)
![image](https://github.com/bnb-chain/greenfield-js-sdk/assets/92920845/40f8a790-29d1-4047-aed7-fc749fea3d36)

Even if I omit it, and do broadcast immediately, the following error comes out:
![image](https://github.com/bnb-chain/greenfield-js-sdk/assets/92920845/c54682db-1519-4a1b-be8e-1c60ceed84c1)
![image](https://github.com/bnb-chain/greenfield-js-sdk/assets/92920845/7d219384-0ac5-4902-aa8c-c763b5b09274)
Error: missing value for field creaator of type string                                                                          

apparently the mistake is in the wrong word here:
https://github.com/bnb-chain/greenfield-js-sdk/blob/226bb7aba25e641bcde011f027643163e29a35a2/packages/chain-sdk/src/messages/greenfield/payment/MsgCreatePaymentAccount.ts#L10

**Comment by deepcrazy** [comment]
Hi there, Can you provide the list of steps you're doing for reproducing please?

Also, Can you also share your code (if any) written for this functionality for testing on our end please?
